/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * api
 */
export interface AggregationInfluxQuery {
  description?: string
  fields?: FieldInfluxQuery[]
  title?: string
}

export interface DeviceDataQuery {
  /** e.g. ["68569ea8e0dd6ef874daac15","68569ea8e0dd6ef874daac16"] */
  device: string
  encode?: string
  /** required (e.g. "1m") */
  every: string
  /** e.g. "mean", "max" */
  fn: string
  /** e.g. ["speed","alt"] */
  sensors: DeviceDataQueryField[]
  /** e.g. "-10d", "2023-06-01T00:00:00Z" */
  start: string
  /** required */
  stop: string
}

export interface DeviceDataQueryField {
  field?: string[]
  index?: string
  sensor?: string
}

export interface DeviceField {
  field?: string
  label?: string
  path?: string
  unit?: string
}

export interface DeviceMapper {
  fields: DeviceField[]
  index: string
  sensor: string
}

export interface FieldInfluxQuery {
  description?: string
  example?: unknown
  in?: string
  name?: string
  required?: boolean
  title?: string
  type?: string
}

export interface HttpError {
  code?: number
  error?: unknown
  message?: string
}

export interface QueryResult {
  field?: string
  index?: string
  result?: string
  sensor?: string
  time?: string
  value?: unknown
}

export interface SensorSchema {
  fields?: string[]
  sensor?: string
  title?: string
  units?: string[]
}

export type GetDevicesDataByIdPost200 = {[key: string]: QueryResult[]}

export type GetFunctionsSchema200 = {[key: string]: AggregationInfluxQuery}
