/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * api
 */
import {useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  DeviceDataQuery,
  DeviceMapper,
  GetDevicesDataByIdPost200,
  GetFunctionsSchema200,
  HttpError,
  SensorSchema,
} from './api.schemas'

import {ingestionApiServiceInstance} from '../../../axios/axios'
import type {ErrorType, BodyType} from '../../../axios/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get devices data by ID (Post)
 */
export const getDevicesDataByIdPost = (
  deviceDataQuery: BodyType<DeviceDataQuery>,
  options?: SecondParameter<typeof ingestionApiServiceInstance>,
  signal?: AbortSignal,
) => {
  return ingestionApiServiceInstance<GetDevicesDataByIdPost200>(
    {
      url: `/device`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: deviceDataQuery,
      signal,
    },
    options,
  )
}

export const getGetDevicesDataByIdPostQueryKey = (
  deviceDataQuery: DeviceDataQuery,
) => {
  return [`/device`, deviceDataQuery] as const
}

export const getGetDevicesDataByIdPostQueryOptions = <
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetDevicesDataByIdPostQueryKey(deviceDataQuery)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDevicesDataByIdPost>>
  > = ({signal}) =>
    getDevicesDataByIdPost(deviceDataQuery, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetDevicesDataByIdPostQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDevicesDataByIdPost>>
>
export type GetDevicesDataByIdPostQueryError = ErrorType<HttpError>

export function useGetDevicesDataByIdPost<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
          TError,
          Awaited<ReturnType<typeof getDevicesDataByIdPost>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDevicesDataByIdPost<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
          TError,
          Awaited<ReturnType<typeof getDevicesDataByIdPost>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDevicesDataByIdPost<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get devices data by ID (Post)
 */

export function useGetDevicesDataByIdPost<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetDevicesDataByIdPostQueryOptions(
    deviceDataQuery,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetDevicesDataByIdPostSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetDevicesDataByIdPostQueryKey(deviceDataQuery)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDevicesDataByIdPost>>
  > = ({signal}) =>
    getDevicesDataByIdPost(deviceDataQuery, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetDevicesDataByIdPostSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDevicesDataByIdPost>>
>
export type GetDevicesDataByIdPostSuspenseQueryError = ErrorType<HttpError>

export function useGetDevicesDataByIdPostSuspense<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDevicesDataByIdPostSuspense<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDevicesDataByIdPostSuspense<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get devices data by ID (Post)
 */

export function useGetDevicesDataByIdPostSuspense<
  TData = Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
  TError = ErrorType<HttpError>,
>(
  deviceDataQuery: DeviceDataQuery,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDevicesDataByIdPost>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetDevicesDataByIdPostSuspenseQueryOptions(
    deviceDataQuery,
    options,
  )

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get device fields by ID
 */
export const getDeviceFieldsById = (
  deviceId: string,
  options?: SecondParameter<typeof ingestionApiServiceInstance>,
  signal?: AbortSignal,
) => {
  return ingestionApiServiceInstance<DeviceMapper[]>(
    {url: `/device/fields/${deviceId}`, method: 'GET', signal},
    options,
  )
}

export const getGetDeviceFieldsByIdQueryKey = (deviceId: string) => {
  return [`/device/fields/${deviceId}`] as const
}

export const getGetDeviceFieldsByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetDeviceFieldsByIdQueryKey(deviceId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDeviceFieldsById>>
  > = ({signal}) => getDeviceFieldsById(deviceId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!deviceId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceFieldsById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetDeviceFieldsByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDeviceFieldsById>>
>
export type GetDeviceFieldsByIdQueryError = ErrorType<HttpError>

export function useGetDeviceFieldsById<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceFieldsById>>,
          TError,
          Awaited<ReturnType<typeof getDeviceFieldsById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDeviceFieldsById<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceFieldsById>>,
          TError,
          Awaited<ReturnType<typeof getDeviceFieldsById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDeviceFieldsById<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get device fields by ID
 */

export function useGetDeviceFieldsById<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetDeviceFieldsByIdQueryOptions(deviceId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetDeviceFieldsByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetDeviceFieldsByIdQueryKey(deviceId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDeviceFieldsById>>
  > = ({signal}) => getDeviceFieldsById(deviceId, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getDeviceFieldsById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetDeviceFieldsByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDeviceFieldsById>>
>
export type GetDeviceFieldsByIdSuspenseQueryError = ErrorType<HttpError>

export function useGetDeviceFieldsByIdSuspense<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDeviceFieldsByIdSuspense<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetDeviceFieldsByIdSuspense<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get device fields by ID
 */

export function useGetDeviceFieldsByIdSuspense<
  TData = Awaited<ReturnType<typeof getDeviceFieldsById>>,
  TError = ErrorType<HttpError>,
>(
  deviceId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getDeviceFieldsById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetDeviceFieldsByIdSuspenseQueryOptions(
    deviceId,
    options,
  )

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get functions schema
 */
export const getFunctionsSchema = (
  options?: SecondParameter<typeof ingestionApiServiceInstance>,
  signal?: AbortSignal,
) => {
  return ingestionApiServiceInstance<GetFunctionsSchema200>(
    {url: `/device/schema`, method: 'GET', signal},
    options,
  )
}

export const getGetFunctionsSchemaQueryKey = () => {
  return [`/device/schema`] as const
}

export const getGetFunctionsSchemaQueryOptions = <
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFunctionsSchema>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof ingestionApiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFunctionsSchemaQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFunctionsSchema>>
  > = ({signal}) => getFunctionsSchema(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getFunctionsSchema>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetFunctionsSchemaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFunctionsSchema>>
>
export type GetFunctionsSchemaQueryError = ErrorType<HttpError>

export function useGetFunctionsSchema<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFunctionsSchema>>,
          TError,
          Awaited<ReturnType<typeof getFunctionsSchema>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetFunctionsSchema<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFunctionsSchema>>,
          TError,
          Awaited<ReturnType<typeof getFunctionsSchema>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetFunctionsSchema<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get functions schema
 */

export function useGetFunctionsSchema<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetFunctionsSchemaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetFunctionsSchemaSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getFunctionsSchema>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof ingestionApiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFunctionsSchemaQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFunctionsSchema>>
  > = ({signal}) => getFunctionsSchema(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getFunctionsSchema>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetFunctionsSchemaSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFunctionsSchema>>
>
export type GetFunctionsSchemaSuspenseQueryError = ErrorType<HttpError>

export function useGetFunctionsSchemaSuspense<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetFunctionsSchemaSuspense<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetFunctionsSchemaSuspense<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get functions schema
 */

export function useGetFunctionsSchemaSuspense<
  TData = Awaited<ReturnType<typeof getFunctionsSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getFunctionsSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetFunctionsSchemaSuspenseQueryOptions(options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get sensor schema
 */
export const getSensorSchema = (
  options?: SecondParameter<typeof ingestionApiServiceInstance>,
  signal?: AbortSignal,
) => {
  return ingestionApiServiceInstance<SensorSchema[]>(
    {url: `/device/sensor/schema`, method: 'GET', signal},
    options,
  )
}

export const getGetSensorSchemaQueryKey = () => {
  return [`/device/sensor/schema`] as const
}

export const getGetSensorSchemaQueryOptions = <
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSensorSchema>>, TError, TData>
  >
  request?: SecondParameter<typeof ingestionApiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSensorSchemaQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSensorSchema>>> = ({
    signal,
  }) => getSensorSchema(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getSensorSchema>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetSensorSchemaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSensorSchema>>
>
export type GetSensorSchemaQueryError = ErrorType<HttpError>

export function useGetSensorSchema<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSensorSchema>>,
          TError,
          Awaited<ReturnType<typeof getSensorSchema>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetSensorSchema<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSensorSchema>>,
          TError,
          Awaited<ReturnType<typeof getSensorSchema>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetSensorSchema<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get sensor schema
 */

export function useGetSensorSchema<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetSensorSchemaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetSensorSchemaSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getSensorSchema>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof ingestionApiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSensorSchemaQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSensorSchema>>> = ({
    signal,
  }) => getSensorSchema(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSensorSchema>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetSensorSchemaSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSensorSchema>>
>
export type GetSensorSchemaSuspenseQueryError = ErrorType<HttpError>

export function useGetSensorSchemaSuspense<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetSensorSchemaSuspense<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetSensorSchemaSuspense<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get sensor schema
 */

export function useGetSensorSchemaSuspense<
  TData = Awaited<ReturnType<typeof getSensorSchema>>,
  TError = ErrorType<HttpError>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getSensorSchema>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof ingestionApiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetSensorSchemaSuspenseQueryOptions(options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
