/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * api
 */
/**
 * example:"owner,admin,employee,guest"`
 */
export type AccessUpdateDtoRole =
  (typeof AccessUpdateDtoRole)[keyof typeof AccessUpdateDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccessUpdateDtoRole = {
  admin: 'admin',
  employee: 'employee',
  guest: 'guest',
} as const

export interface AccessUpdateDto {
  email?: string
  /** example:"owner,admin,employee,guest"` */
  role: AccessUpdateDtoRole
}

export type ActionConfig = {[key: string]: unknown}

export interface Action {
  config?: ActionConfig
  description?: string
  /** "user_dashboard", "mobile_app" */
  target?: string[]
  type?: ActionType
}

export type ActionType = (typeof ActionType)[keyof typeof ActionType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionType = {
  WebhookAction: 'webhook',
  APICallAction: 'api_call',
  LogAction: 'log',
  EmailAction: 'email',
  SMSAction: 'sms',
} as const

export type ApiConnectorAutofill = {[key: string]: string}

export type ApiConnectorFilters = {[key: string]: string}

export type ApiConnectorVisibleWhen = {[key: string]: string}

export interface ApiConnector {
  autofill?: ApiConnectorAutofill
  default?: unknown
  description?: string
  example?: unknown
  filters?: ApiConnectorFilters
  /** اضافه شد برای آرایه‌ها و struct تو در تو */
  items?: unknown
  kind?: string
  name?: string
  options?: string[]
  order?: number
  readonly?: boolean
  ref?: string
  required?: boolean
  type?: string
  value?: unknown
  visibleWhen?: ApiConnectorVisibleWhen
}

/**
 * system, user, assistant
 */
export type ChatMessageRole =
  (typeof ChatMessageRole)[keyof typeof ChatMessageRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatMessageRole = {
  system: 'system',
  user: 'user',
  assistant: 'assistant',
} as const

export interface ChatMessage {
  content: string
  /** system, user, assistant */
  role: ChatMessageRole
}

export interface ChatRequest {
  messages?: ChatMessage[]
  /** deepseek-r1:32b, deepseek-coder-v2:16b, yi:34b */
  model?: string
  stream?: boolean
}

export interface ChatResponse {
  content?: string
  done?: boolean
}

export interface CheckEmailDto {
  email: string
}

export interface CheckEmailResponseDto {
  isRegistered?: boolean
  message?: string
}

export interface Condition {
  and?: LogicalCondition[]
  /** device.ID */
  deviceId?: string
  or?: LogicalCondition[]
  thresholds?: ThresholdCondition[]
}

export type ConditionOperator =
  (typeof ConditionOperator)[keyof typeof ConditionOperator]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConditionOperator = {
  GreaterThan: 'greater_than',
  LessThan: 'less_than',
  Equal: 'equal',
  NotEqual: 'not_equal',
} as const

export type ConnectorSchemaConfigSchema = {[key: string]: ApiConnector}

export type ConnectorSchemaReviewSchema = {[key: string]: ApiConnector}

export interface ConnectorSchema {
  active?: boolean
  configSchema?: ConnectorSchemaConfigSchema
  description?: string
  name?: string
  protocolType?: ProtocolType
  reviewSchema?: ConnectorSchemaReviewSchema
  status?: boolean
  target?: string[]
}

export type ControllerSchemaConfigSchema = {[key: string]: ApiConnector}

export type ControllerSchemaReviewSchema = {[key: string]: ApiConnector}

export interface ControllerSchema {
  active?: boolean
  configSchema?: ControllerSchemaConfigSchema
  description?: string
  name?: string
  protocolType?: ProtocolType
  reviewSchema?: ControllerSchemaReviewSchema
  status?: boolean
}

export type DashboardSettings = {[key: string]: unknown}

export type DashboardViewsItem = {[key: string]: unknown}

export interface Dashboard {
  _id?: string
  active?: boolean
  createdAt?: string
  creator?: UserPopulate
  description?: string
  dynamicBy?: string
  name?: string
  owner?: string
  pin?: boolean
  settings?: DashboardSettings
  updatedAt?: string
  views?: DashboardViewsItem[]
  workspace?: string
}

export type DashboardCreateDtoSettings = {[key: string]: unknown}

export type DashboardCreateDtoViewsItem = {[key: string]: unknown}

export interface DashboardCreateDto {
  description?: string
  dynamicBy?: string
  name: string
  settings?: DashboardCreateDtoSettings
  views?: DashboardCreateDtoViewsItem[]
}

export type DashboardMemberGrantedCreateDtoRole =
  (typeof DashboardMemberGrantedCreateDtoRole)[keyof typeof DashboardMemberGrantedCreateDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardMemberGrantedCreateDtoRole = {
  admin: 'admin',
  employee: 'employee',
  guest: 'guest',
} as const

export interface DashboardMemberGrantedCreateDto {
  dashboardId: string
  memberId: string
  role: DashboardMemberGrantedCreateDtoRole
}

export type DashboardPopulateSettings = {[key: string]: unknown}

export type DashboardPopulateViewsItem = {[key: string]: unknown}

export interface DashboardPopulate {
  _id?: string
  active?: boolean
  createdAt?: string
  creator?: UserPopulate
  description?: string
  dynamicBy?: GroupTemplate
  name?: string
  owner?: string
  pin?: boolean
  settings?: DashboardPopulateSettings
  updatedAt?: string
  views?: DashboardPopulateViewsItem[]
  workspace?: string
}

export type DashboardTemplateSource = {[key: string]: unknown}

export interface DashboardTemplate {
  _id?: string
  category?: string
  coverImage?: string
  description?: string
  name: string
  source?: DashboardTemplateSource
}

export type DashboardTemplateCreateDtoSource = {[key: string]: unknown}

export interface DashboardTemplateCreateDto {
  category?: string
  coverImage?: string
  description?: string
  name: string
  source?: DashboardTemplateCreateDtoSource
}

export type DashboardTemplateUpdateDtoSource = {[key: string]: unknown}

export interface DashboardTemplateUpdateDto {
  category?: string
  coverImage?: string
  description?: string
  name?: string
  source?: DashboardTemplateUpdateDtoSource
}

export type DashboardUpdateDtoSettings = {[key: string]: unknown}

export type DashboardUpdateDtoViewsItem = {[key: string]: unknown}

export interface DashboardUpdateDto {
  active?: boolean
  description?: string
  dynamicBy?: string
  name?: string
  pin?: boolean
  settings?: DashboardUpdateDtoSettings
  views?: DashboardUpdateDtoViewsItem[]
}

export interface Dependencies {
  devices?: string[]
  groups?: string[]
}

export interface DependenciesPopulate {
  devices?: Device[]
  groups?: DeviceGroup[]
}

export interface Device {
  createdAt?: string
  description?: string
  deviceId?: string
  features?: DeviceFeature[]
  group?: string
  id?: string
  name?: string
  owner?: string
  publishedAt?: string
  role?: string
  saveData?: boolean
  status?: boolean
  tags?: string[]
  type?: string
  updatedAt?: string
  workspace?: string
}

export type DeviceActuatorParams = {[key: string]: DeviceActuatorParam}

export interface DeviceActuator {
  command?: string
  id: string
  name?: string
  params?: DeviceActuatorParams
}

export interface DeviceActuatorParam {
  default?: unknown
  description?: string
  dynamic?: boolean
  id: string
  key: string
  max?: number
  min?: number
  name: string
  options?: string[]
  required: boolean
  type: string
  value?: string
}

export interface DeviceCloneDto {
  deviceFeatures?: DeviceFeature[]
  deviceId: string
  deviceName: string
  groupId?: string
  roles?: string
}

export type DeviceConnectorCreateDtoConnector = {[key: string]: unknown}

export type DeviceConnectorCreateDtoController = {[key: string]: unknown}

export interface DeviceConnectorCreateDto {
  actuators?: DeviceActuator[]
  connector: DeviceConnectorCreateDtoConnector
  controller?: DeviceConnectorCreateDtoController
  device: string
  id?: string
  mapper?: DeviceMapper[]
  name: string
  type: string
}

export type DeviceConnectorPopulateConnector = {[key: string]: unknown}

export type DeviceConnectorPopulateController = {[key: string]: unknown}

export interface DeviceConnectorPopulate {
  active?: boolean
  actuators?: DeviceActuator[]
  connector?: DeviceConnectorPopulateConnector
  controller?: DeviceConnectorPopulateController
  createdAt?: string
  creator?: UserPopulate
  device?: Device
  id?: string
  mapper?: DeviceMapper[]
  name?: string
  owner?: UserPopulate
  type?: string
  updatedAt?: string
  workspace?: Workspace
}

export type DeviceConnectorUpdateDtoConnector = {[key: string]: unknown}

export type DeviceConnectorUpdateDtoController = {[key: string]: unknown}

export interface DeviceConnectorUpdateDto {
  active?: boolean
  actuators?: DeviceActuator[]
  connector?: DeviceConnectorUpdateDtoConnector
  controller?: DeviceConnectorUpdateDtoController
  device?: string
  mapper?: DeviceMapper[]
  name?: string
  type?: string
  workspace?: string
}

export type DeviceCreateDtoType =
  (typeof DeviceCreateDtoType)[keyof typeof DeviceCreateDtoType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeviceCreateDtoType = {
  gateway: 'gateway',
  sensor: 'sensor',
  controller: 'controller',
  processor: 'processor',
  ipCamera: 'ipCamera',
} as const

export interface DeviceCreateDto {
  description?: string
  deviceId?: string
  features?: DeviceFeature[]
  group?: string
  id?: string
  name: string
  role?: string
  saveData?: boolean
  tags?: string[]
  type: DeviceCreateDtoType
}

export type DeviceDataData = {[key: string]: unknown}

export interface DeviceData {
  connector?: string
  createdAt?: string
  data?: DeviceDataData
  device?: string
  id?: string
  updatedAt?: string
  workspace?: string
}

export interface DeviceFeature {
  field?: string
  label?: string
  path?: string
  unit?: string
  value?: string
}

export interface DeviceField {
  field?: string
  label?: string
  path?: string
  unit?: string
}

export interface DeviceForOption {
  description?: string
  deviceId?: string
  id?: string
  name?: string
  type?: string
}

export interface DeviceGroup {
  createdAt?: string
  description?: string
  features?: DeviceFeature[]
  id?: string
  name?: string
  owner?: string
  roles?: DeviceRole[]
  template?: string
  updatedAt?: string
  workspace?: string
}

export interface DeviceGroupCreateDto {
  description?: string
  features?: DeviceFeature[]
  id?: string
  name: string
  roles?: DeviceRole[]
  template?: string
}

export interface DeviceGroupImportDto {
  cloneDeviceId: string
  deviceFeatures: string
  deviceId: string
  deviceName: string
  groupFeatures: string
  groupId: string
  groupName: string
}

export interface DeviceGroupPopulate {
  description?: string
  features?: DeviceFeature[]
  id?: string
  name: string
  roles?: DeviceRole[]
  template?: GroupTemplate
}

export interface DeviceGroupUpdateDto {
  description?: string
  features?: DeviceFeature[]
  name?: string
  roles?: DeviceRole[]
  template?: string
}

export interface DeviceGroupWithDevices {
  createdAt?: string
  description?: string
  devices?: unknown[]
  features?: DeviceFeature[]
  id?: string
  name?: string
  owner?: string
  roles?: DeviceRole[]
  template?: GroupTemplate
  updatedAt?: string
  workspace?: string
}

export interface DeviceGroupWithTemplateImportDto {
  deviceFeatures: string
  deviceId: string
  deviceName: string
  groupFeatures: string
  groupId: string
  groupName: string
  role: string
}

export interface DeviceMapper {
  fields: DeviceField[]
  index: string
  sensor: string
}

export interface DevicePopulate {
  createdAt?: string
  description?: string
  deviceId?: string
  features?: DeviceFeature[]
  group?: DeviceGroup
  id?: string
  name?: string
  publishedAt?: string
  role?: string
  saveData?: boolean
  status?: boolean
  tags?: DeviceTagPopulate[]
  type?: string
  updatedAt?: string
}

export interface DeviceRole {
  device: string
  role: string
}

export interface DeviceTag {
  createdAt?: string
  description?: string
  id?: string
  name?: string
  owner?: string
  updatedAt?: string
  workspace?: string
}

export interface DeviceTagCreateDto {
  description?: string
  id?: string
  name: string
}

export interface DeviceTagPopulate {
  description?: string
  id?: string
  name?: string
}

export interface DeviceTagUpdateDto {
  description?: string
  name?: string
}

export type DeviceUpdateDtoType =
  (typeof DeviceUpdateDtoType)[keyof typeof DeviceUpdateDtoType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeviceUpdateDtoType = {
  gateway: 'gateway',
  sensor: 'sensor',
  controller: 'controller',
  processor: 'processor',
  ipCamera: 'ipCamera',
} as const

export interface DeviceUpdateDto {
  description?: string
  deviceId?: string
  features?: DeviceFeature[]
  group?: string
  name?: string
  role?: string
  saveData?: boolean
  tags?: string[]
  type?: DeviceUpdateDtoType
}

export interface FilterField {
  field?: string
  operators?: FilterOperator[]
  ref?: string
  type?: string
}

export interface FilterOperator {
  inputType?: string
  op?: string
  title?: string
}

export interface GroupTemplate {
  createdAt?: string
  id?: string
  name?: string
  owner?: string
  roles?: string[]
  updatedAt?: string
  workspace?: string
}

export interface GroupTemplateCreateDto {
  id?: string
  name: string
  roles: TemplateRoleCreateDto[]
}

export interface GroupTemplatePopulate {
  id?: string
  name: string
  roles: TemplateRole[]
}

export interface GroupTemplateUpdateDto {
  name?: string
  roles?: UpdateTemplateRoles
}

export interface GroupTemplateWithDevices {
  createdAt?: string
  groups?: string[]
  id?: string
  name?: string
  owner?: string
  roles?: TemplateRole[]
  updatedAt?: string
  workspace?: string
}

export interface HttpError {
  code?: number
  error?: unknown
  message?: string
}

export interface HttpResponse {
  code?: number
  data?: unknown
  message?: string
}

export type ItemProperty = {[key: string]: unknown}

export interface Item {
  hide?: boolean
  id?: string
  label?: string
  lock?: boolean
  name?: string
  property?: ItemProperty
  type?: string
}

export interface LogicalCondition {
  and?: LogicalCondition[]
  /** device.ID */
  deviceId?: string
  or?: LogicalCondition[]
  thresholds?: ThresholdCondition[]
}

export interface MqttResponse {
  message?: string
  status?: string
}

export interface Notification {
  createdAt?: string
  device?: string
  expiresAt?: string
  id?: string
  level?: NotificationLevel
  message?: string
  publishedAt?: string
  readBy?: string[]
  status?: NotificationStatus
  title?: string
  type?: NotificationType
  updatedAt?: string
  users?: string[]
  workspace?: string
}

export type NotificationCreateDtoLevel =
  (typeof NotificationCreateDtoLevel)[keyof typeof NotificationCreateDtoLevel]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationCreateDtoLevel = {
  info: 'info',
  warning: 'warning',
  critical: 'critical',
} as const

export interface NotificationCreateDto {
  device?: string
  expiresAt?: string
  level: NotificationCreateDtoLevel
  message: string
  title: string
  type: NotificationType
  users?: string[]
  workspace?: string
}

export type NotificationLevel =
  (typeof NotificationLevel)[keyof typeof NotificationLevel]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationLevel = {
  NotificationLevelInfo: 'info',
  NotificationLevelWarning: 'warning',
  NotificationLevelError: 'error',
  NotificationLevelSuccess: 'success',
} as const

export interface NotificationMarkAsReadDto {
  ids?: string[]
}

export interface NotificationPopulate {
  createdAt?: string
  device?: Device
  expiresAt?: string
  id?: string
  level?: NotificationLevel
  message?: string
  publishedAt?: string
  readBy?: User[]
  status?: NotificationStatus
  title?: string
  type?: NotificationType
  updatedAt?: string
  users?: User[]
  workspace?: Workspace
}

export type NotificationStatus =
  (typeof NotificationStatus)[keyof typeof NotificationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationStatus = {
  NotificationStatusQueued: 'queued',
  NotificationStatusSent: 'sent',
  NotificationStatusSeen: 'seen',
  NotificationStatusFailed: 'failed',
  NotificationStatusArchived: 'archived',
} as const

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
  NotificationTypeDevice: 'device',
  NotificationTypeSystem: 'system',
  NotificationTypeUserAction: 'user_action',
} as const

export interface PaginationDashboard {
  filters?: FilterField[]
  list?: Dashboard[]
  pageCount?: number
  total?: number
}

export interface PaginationDashboardTemplate {
  filters?: FilterField[]
  list?: DashboardTemplate[]
  pageCount?: number
  total?: number
}

export interface PaginationDevice {
  filters?: FilterField[]
  list?: Device[]
  pageCount?: number
  total?: number
}

export interface PaginationDeviceConnectorPopulate {
  filters?: FilterField[]
  list?: DeviceConnectorPopulate[]
  pageCount?: number
  total?: number
}

export interface PaginationDeviceData {
  filters?: FilterField[]
  list?: DeviceData[]
  pageCount?: number
  total?: number
}

export interface PaginationDeviceGroupPopulate {
  filters?: FilterField[]
  list?: DeviceGroupPopulate[]
  pageCount?: number
  total?: number
}

export interface PaginationDeviceGroupWithDevices {
  filters?: FilterField[]
  list?: DeviceGroupWithDevices[]
  pageCount?: number
  total?: number
}

export interface PaginationDevicePopulate {
  filters?: FilterField[]
  list?: DevicePopulate[]
  pageCount?: number
  total?: number
}

export interface PaginationDeviceTagPopulate {
  filters?: FilterField[]
  list?: DeviceTagPopulate[]
  pageCount?: number
  total?: number
}

export interface PaginationGroupTemplatePopulate {
  filters?: FilterField[]
  list?: GroupTemplatePopulate[]
  pageCount?: number
  total?: number
}

export interface PaginationGroupTemplateWithDevices {
  filters?: FilterField[]
  list?: GroupTemplateWithDevices[]
  pageCount?: number
  total?: number
}

export interface PaginationNotification {
  filters?: FilterField[]
  list?: Notification[]
  pageCount?: number
  total?: number
}

export interface PaginationScada {
  filters?: FilterField[]
  list?: Scada[]
  pageCount?: number
  total?: number
}

export interface PaginationShare {
  filters?: FilterField[]
  list?: Share[]
  pageCount?: number
  total?: number
}

export interface PaginationTemplateRole {
  filters?: FilterField[]
  list?: TemplateRole[]
  pageCount?: number
  total?: number
}

export interface PaginationVision {
  filters?: FilterField[]
  list?: Vision[]
  pageCount?: number
  total?: number
}

export interface PaginationWidget {
  filters?: FilterField[]
  list?: Widget[]
  pageCount?: number
  total?: number
}

export interface PaginationWorkspace {
  filters?: FilterField[]
  list?: Workspace[]
  pageCount?: number
  total?: number
}

export interface PaginationWorkspaceInviteMemberResponse {
  filters?: FilterField[]
  list?: WorkspaceInviteMemberResponse[]
  pageCount?: number
  total?: number
}

export interface Profile {
  align?: string
  bkcolor?: string
  gridType?: string
  height?: number
  margin?: number
  viewRenderDelay?: number
  width?: number
}

export type ProtocolType = (typeof ProtocolType)[keyof typeof ProtocolType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProtocolType = {
  MQTTProtocol: 'mqtt',
  VirtualProtocol: 'virtual',
} as const

export interface Publish {
  publishedAt?: string
  publishedView?: ScadaView
}

export interface RefreshToken {
  accessToken: string
  refreshToken: string
}

export interface RefreshTokenDto {
  refreshToken: string
  /** ID of the make access token */
  workspaceId?: string
}

export interface RequestDemoDto {
  company: string
  email: string
  name: string
  phone: string
}

export interface ResetPasswordDto {
  email: string
}

export interface Rule {
  actions?: Action[]
  conditions?: Condition
  description?: string
  devices?: string[]
  id?: string
  lastTriggered?: string
  name?: string
  priority?: number
  status?: RuleStatus
  user?: string
}

export interface RuleCreateDto {
  actions?: Action[]
  conditions?: Condition
  description?: string
  devices?: string[]
  name?: string
  priority?: number
}

export interface RulePopulate {
  actions?: Action[]
  conditions?: Condition
  description?: string
  devices?: Device[]
  id?: string
  lastTriggered?: string
  name?: string
  priority?: number
  status?: RuleStatus
  user?: string
}

export type RuleStatus = (typeof RuleStatus)[keyof typeof RuleStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleStatus = {
  ActiveStatus: 'active',
  InactiveStatus: 'inactive',
  PausedStatus: 'paused',
} as const

export type RuleUpdateDtoStatus =
  (typeof RuleUpdateDtoStatus)[keyof typeof RuleUpdateDtoStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleUpdateDtoStatus = {
  paused: 'paused',
  inactive: 'inactive',
  active: 'active',
} as const

export interface RuleUpdateDto {
  actions?: Action[]
  conditions?: Condition
  description?: string
  devices?: string[]
  name?: string
  priority?: number
  status?: RuleUpdateDtoStatus
}

export interface Scada {
  active?: boolean
  createdAt?: string
  creator?: User
  dependencies?: DependenciesPopulate
  id?: string
  name?: string
  owner?: User
  publishedAt?: string
  publishedView?: ScadaView
  updatedAt?: string
  view?: ScadaView
  workspace?: Workspace
}

export interface ScadaAddViewDto {
  view?: ScadaView
}

export interface ScadaAllViewsPopulate {
  active?: boolean
  createdAt?: string
  creator?: User
  dependencies?: DependenciesPopulate
  id?: string
  name?: string
  owner?: User
  publishedAt?: string
  publishedViews?: ScadaView[]
  updatedAt?: string
  views?: ScadaView[]
  workspace?: Workspace
}

export interface ScadaCreateDto {
  dependencies?: Dependencies
  name?: string
  view?: ScadaView
}

export interface ScadaUpdateDto {
  dependencies?: Dependencies
  name?: string
}

export type ScadaViewItems = {[key: string]: Item}

export type ScadaViewVariables = {[key: string]: unknown}

export interface ScadaView {
  id?: string
  items?: ScadaViewItems
  name?: string
  profile?: Profile
  svgcontent?: string
  type?: string
  variables?: ScadaViewVariables
}

export interface ScadaViewUpdateDto {
  view?: ScadaView
}

export type ScriptSchemaParams = {[key: string]: unknown}

export interface ScriptSchema {
  actuators?: DeviceActuator[]
  description?: string
  icon?: string
  mapper?: DeviceMapper[]
  name?: string
  params?: ScriptSchemaParams
  requirements?: string
  script?: string
  type?: string
  version?: string
}

export interface SendEmailDto {
  body: string
  subject: string
  to: string
}

export type ShareMetaData = {[key: string]: unknown}

export interface Share {
  _id?: string
  active?: boolean
  apiKey?: string
  createdAt?: string
  creator?: string
  description?: string
  expireTime?: string
  metaData?: ShareMetaData
  target?: string
  targetId: string
  title?: string
  updatedAt?: string
  workspace?: string
}

export interface ShareAuth {
  accessToken?: string
  share?: Share
}

export type ShareCreateDtoMetaData = {[key: string]: unknown}

export interface ShareCreateDto {
  description?: string
  expireTime?: string
  metaData?: ShareCreateDtoMetaData
  password: string
  targetId: string
  title?: string
}

export interface ShareDataDto {
  apiKey: string
  /** @minLength 8 */
  password: string
}

export type ShareUpdateDtoMetaData = {[key: string]: unknown}

export interface ShareUpdateDto {
  active?: boolean
  description?: string
  expireTime?: string
  metaData?: ShareUpdateDtoMetaData
  password?: string
  title?: string
}

export interface ShortenUrlResponse {
  code?: string
  expiresAt?: string
  originalUrl?: string
  shortUrl?: string
}

export interface SwitchAccountDto {
  /** ID of the workspace to switch to */
  workspaceId: string
}

export interface TemplateRole {
  id?: string
  required?: boolean
  role?: string
  workspace?: string
}

export interface TemplateRoleCreateDto {
  required: boolean
  role: string
}

export interface TemplateRoleUpdateDto {
  id: string
  required?: boolean
  role?: string
}

export interface ThresholdCondition {
  field?: string
  operator?: ConditionOperator
  value?: unknown
}

export interface UpdatePasswordDto {
  /** @minLength 8 */
  newPassword: string
  token: string
}

export interface UpdateTemplateRoles {
  creates?: TemplateRoleCreateDto[]
  deletes?: string[]
  update?: TemplateRoleUpdateDto[]
}

export interface UploadedFile {
  bucket?: string
  fileKey?: string
  mimetype?: string
  originalname?: string
  size?: number
}

/**
 * example:"owner,admin,employee,guest"`
 */
export type UserRole = (typeof UserRole)[keyof typeof UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  admin: 'admin',
  employee: 'employee',
  guest: 'guest',
} as const

export interface User {
  _id?: string
  createdAt?: string
  email: string
  name: string
  phone?: string
  /** example:"owner,admin,employee,guest"` */
  role: UserRole
  updatedAt?: string
  userSetting: UserSettings
  userState: UserState
}

export interface UserAuthTokenMediaMTXDto {
  action?: string
  id?: string
  ip?: string
  password?: string
  path?: string
  protocol?: string
  query?: string
  token?: string
  user?: string
}

/**
 * example:"owner,admin,employee,guest"`
 */
export type UserCreateDtoRole =
  (typeof UserCreateDtoRole)[keyof typeof UserCreateDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreateDtoRole = {
  admin: 'admin',
  employee: 'employee',
  guest: 'guest',
} as const

export interface UserCreateDto {
  email: string
  id?: string
  name: string
  /**
   * Password must be at least 8 characters long
   * @minLength 8
   */
  password: string
  /** Phone can be empty, but if provided, must be unique and valid */
  phone?: string
  /** example:"owner,admin,employee,guest"` */
  role: UserCreateDtoRole
}

export type UserInformationInformation = {[key: string]: unknown}

export interface UserInformation {
  _id?: string
  createdAt?: string
  information?: UserInformationInformation
  updatedAt?: string
}

export type UserInformationCreateDtoInformation = {[key: string]: unknown}

export interface UserInformationCreateDto {
  information: UserInformationCreateDtoInformation
}

export interface UserLogin {
  accessToken?: string
  refreshToken?: string
}

export interface UserLoginDto {
  email: string
  /** @minLength 8 */
  password: string
  workspaceId?: string
}

export interface UserPopulate {
  _id?: string
  name?: string
}

export interface UserRegisterDto {
  email: string
  id?: string
  name: string
  /**
   * Password must be at least 8 characters long
   * @minLength 8
   */
  password: string
  /** Phone can be empty, but if provided, must be unique and valid */
  phone?: string
}

export type UserSettingsTheme =
  (typeof UserSettingsTheme)[keyof typeof UserSettingsTheme]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSettingsTheme = {
  light: 'light',
  dark: 'dark',
} as const

export interface UserSettings {
  isTwoFAEnabled: boolean
  theme: UserSettingsTheme
}

export interface UserState {
  countTry2FA?: number
  countTryLogin?: number
  lastUpdate2FA?: string
  pending2FAVerification?: boolean
}

export interface UserUpdateDto {
  name?: string
}

export interface Verify2FACodeDto {
  code: string
}

export type VisionVision = {[key: string]: unknown}

export interface Vision {
  createdAt?: string
  creator?: User
  description?: string
  id?: string
  name?: string
  owner?: User
  snapshot?: string
  updatedAt?: string
  vision?: VisionVision
  workspace?: Workspace
}

export type VisionCreateDtoVision = {[key: string]: unknown}

export interface VisionCreateDto {
  description?: string
  name: string
  vision?: VisionCreateDtoVision
}

export type VisionUpdateDtoVision = {[key: string]: unknown}

export interface VisionUpdateDto {
  description?: string
  name?: string
  snapshot?: string
  vision?: VisionUpdateDtoVision
}

export type WidgetConfig = {[key: string]: unknown}

export interface Widget {
  _id?: string
  config?: WidgetConfig
  createdAt?: string
  creator?: string
  owner?: string
  updatedAt?: string
  workspace?: string
}

export type WidgetCreateDtoConfig = {[key: string]: unknown}

export interface WidgetCreateDto {
  config: WidgetCreateDtoConfig
}

export type WidgetUpdateDtoConfig = {[key: string]: unknown}

export interface WidgetUpdateDto {
  config?: WidgetUpdateDtoConfig
}

export type WorkspaceSettings = {[key: string]: unknown}

export interface Workspace {
  _id?: string
  active: boolean
  createdAt?: string
  description?: string
  name: string
  settings?: WorkspaceSettings
  updatedAt?: string
}

export type WorkspaceCreateDtoSettings = {[key: string]: unknown}

export interface WorkspaceCreateDto {
  description?: string
  name: string
  settings?: WorkspaceCreateDtoSettings
}

/**
 * example:"owner,admin,employee,guest"`
 */
export type WorkspaceInviteMemberCreateDtoRole =
  (typeof WorkspaceInviteMemberCreateDtoRole)[keyof typeof WorkspaceInviteMemberCreateDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkspaceInviteMemberCreateDtoRole = {
  admin: 'admin',
  employee: 'employee',
  guest: 'guest',
} as const

export interface WorkspaceInviteMemberCreateDto {
  email: string
  /** example:"owner,admin,employee,guest"` */
  role: WorkspaceInviteMemberCreateDtoRole
}

export interface WorkspaceInviteMemberResponse {
  email: string
  id?: string
  /** example:"owner,admin,employee,guest"` */
  role?: string
  /** example:"accepted,invited"` */
  status?: string
}

export type WorkspacePopulateSettings = {[key: string]: unknown}

export interface WorkspacePopulate {
  _id?: string
  active: boolean
  createdAt?: string
  creator: User
  description?: string
  name: string
  owner: User
  settings?: WorkspacePopulateSettings
  updatedAt?: string
}

export type AddDeviceGroupWithTemplateFromFileBody = {
  /** File to upload */
  file: Blob
}

/**
 * Workspace Data
 */
export type WorkspaceCreateDtoBody = WorkspaceCreateDto

export type GetAllDevicesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetAllDeviceConnectorsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type GetAllDeviceConnectorByDeviceIdParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type GetLabelExistParams = {
  /**
   * Field label
   */
  label: string
}

export type GetSupportedConnectors200 = {[key: string]: ConnectorSchema}

export type GetSupportedControllers200 = {[key: string]: ControllerSchema}

export type GetAllDeviceDataParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type GetMockGPSRouteParams = {
  /**
   * Lat,long
   */
  start?: string
  /**
   * Lat,long
   */
  end?: string
  /**
   * Distance between sampled points (meters)
   */
  step?: number
}

export type GetAllDevicesForOptionsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetDeviceGroupsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Number of items per page
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetDeviceGroupsWithDevicesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Number of items per page
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type DeleteDeviceGroup200 = {[key: string]: string}

export type GetGroupTemplatesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Number of items per page
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetGroupTemplatesRoleParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Number of items per page
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetGroupTemplatesWithDevicesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Number of items per page
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type DeleteGroupTemplate200 = {[key: string]: string}

export type GetDeviceRulesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type GetAllDeviceTagsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}

export type GetDevicesWithConnectorsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type GetDevicesWithoutConnectorsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
}

export type TriggerDeviceActuatorBody = {[key: string]: unknown}

export type DownloadFileParams = {
  /**
   * JWT token for authentication
   */
  token: string
}

export type GetAllVisionsParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  limit?: number
  /**
   * Filters
   */
  filters?: string
}
