/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * api
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  AddDeviceGroupWithTemplateFromFileBody,
  DownloadFileParams,
  UploadedFile,
} from './api.schemas'

import {apiServiceInstance} from '../../../axios/axios'
import type {ErrorType, BodyType} from '../../../axios/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Upload a file to a workspace
 * @summary Upload a file
 */
export const uploadFile = (
  addDeviceGroupWithTemplateFromFileBody: BodyType<AddDeviceGroupWithTemplateFromFileBody>,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData()
  formData.append(`file`, addDeviceGroupWithTemplateFromFileBody.file)

  return apiServiceInstance<UploadedFile>(
    {
      url: `/files`,
      method: 'POST',
      headers: {'Content-Type': 'multipart/form-data'},
      data: formData,
      signal,
    },
    options,
  )
}

export const getUploadFileMutationOptions = <
  TError = ErrorType<string>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFile>>,
    TError,
    {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
    TContext
  >
  request?: SecondParameter<typeof apiServiceInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
  TContext
> => {
  const mutationKey = ['uploadFile']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFile>>,
    {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>}
  > = (props) => {
    const {data} = props ?? {}

    return uploadFile(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UploadFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFile>>
>
export type UploadFileMutationBody =
  BodyType<AddDeviceGroupWithTemplateFromFileBody>
export type UploadFileMutationError = ErrorType<string>

/**
 * @summary Upload a file
 */
export const useUploadFile = <TError = ErrorType<string>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFile>>,
      TError,
      {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
      TContext
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
  TContext
> => {
  const mutationOptions = getUploadFileMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Upload a file to the public 'assets' bucket
 * @summary Upload a public file
 */
export const uploadPublicFile = (
  addDeviceGroupWithTemplateFromFileBody: BodyType<AddDeviceGroupWithTemplateFromFileBody>,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData()
  formData.append(`file`, addDeviceGroupWithTemplateFromFileBody.file)

  return apiServiceInstance<UploadedFile>(
    {
      url: `/files/public`,
      method: 'POST',
      headers: {'Content-Type': 'multipart/form-data'},
      data: formData,
      signal,
    },
    options,
  )
}

export const getUploadPublicFileMutationOptions = <
  TError = ErrorType<string>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadPublicFile>>,
    TError,
    {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
    TContext
  >
  request?: SecondParameter<typeof apiServiceInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadPublicFile>>,
  TError,
  {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
  TContext
> => {
  const mutationKey = ['uploadPublicFile']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadPublicFile>>,
    {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>}
  > = (props) => {
    const {data} = props ?? {}

    return uploadPublicFile(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UploadPublicFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadPublicFile>>
>
export type UploadPublicFileMutationBody =
  BodyType<AddDeviceGroupWithTemplateFromFileBody>
export type UploadPublicFileMutationError = ErrorType<string>

/**
 * @summary Upload a public file
 */
export const useUploadPublicFile = <
  TError = ErrorType<string>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadPublicFile>>,
      TError,
      {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
      TContext
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadPublicFile>>,
  TError,
  {data: BodyType<AddDeviceGroupWithTemplateFromFileBody>},
  TContext
> => {
  const mutationOptions = getUploadPublicFileMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * List all files in the public 'assets' bucket
 * @summary List public files
 */
export const listPublicFiles = (
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<string[]>(
    {url: `/files/public/list/assets`, method: 'GET', signal},
    options,
  )
}

export const getListPublicFilesQueryKey = () => {
  return [`/files/public/list/assets`] as const
}

export const getListPublicFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listPublicFiles>>, TError, TData>
  >
  request?: SecondParameter<typeof apiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListPublicFilesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublicFiles>>> = ({
    signal,
  }) => listPublicFiles(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof listPublicFiles>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type ListPublicFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicFiles>>
>
export type ListPublicFilesQueryError = ErrorType<string>

export function useListPublicFiles<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicFiles>>,
          TError,
          Awaited<ReturnType<typeof listPublicFiles>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useListPublicFiles<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicFiles>>,
          TError,
          Awaited<ReturnType<typeof listPublicFiles>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useListPublicFiles<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary List public files
 */

export function useListPublicFiles<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getListPublicFilesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getListPublicFilesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof listPublicFiles>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof apiServiceInstance>
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListPublicFilesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublicFiles>>> = ({
    signal,
  }) => listPublicFiles(requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listPublicFiles>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type ListPublicFilesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicFiles>>
>
export type ListPublicFilesSuspenseQueryError = ErrorType<string>

export function useListPublicFilesSuspense<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useListPublicFilesSuspense<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useListPublicFilesSuspense<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary List public files
 */

export function useListPublicFilesSuspense<
  TData = Awaited<ReturnType<typeof listPublicFiles>>,
  TError = ErrorType<string>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicFiles>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getListPublicFilesSuspenseQueryOptions(options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Downloads a public file as raw binary data by its file key.
 * @summary Download a public file
 */
export const downloadPublicFile = (
  filekey: string,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<Blob>(
    {
      url: `/files/public/${filekey}`,
      method: 'GET',
      responseType: 'blob',
      signal,
    },
    options,
  )
}

export const getDownloadPublicFileQueryKey = (filekey: string) => {
  return [`/files/public/${filekey}`] as const
}

export const getDownloadPublicFileQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getDownloadPublicFileQueryKey(filekey)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof downloadPublicFile>>
  > = ({signal}) => downloadPublicFile(filekey, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!filekey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadPublicFile>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type DownloadPublicFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadPublicFile>>
>
export type DownloadPublicFileQueryError = ErrorType<string>

export function useDownloadPublicFile<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadPublicFile>>,
          TError,
          Awaited<ReturnType<typeof downloadPublicFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadPublicFile<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadPublicFile>>,
          TError,
          Awaited<ReturnType<typeof downloadPublicFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadPublicFile<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Download a public file
 */

export function useDownloadPublicFile<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getDownloadPublicFileQueryOptions(filekey, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getDownloadPublicFileSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getDownloadPublicFileQueryKey(filekey)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof downloadPublicFile>>
  > = ({signal}) => downloadPublicFile(filekey, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof downloadPublicFile>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type DownloadPublicFileSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadPublicFile>>
>
export type DownloadPublicFileSuspenseQueryError = ErrorType<string>

export function useDownloadPublicFileSuspense<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadPublicFileSuspense<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadPublicFileSuspense<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Download a public file
 */

export function useDownloadPublicFileSuspense<
  TData = Awaited<ReturnType<typeof downloadPublicFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadPublicFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getDownloadPublicFileSuspenseQueryOptions(
    filekey,
    options,
  )

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Downloads a file as raw binary data by its file key. Requires a valid token.
 * @summary Download a file
 */
export const downloadFile = (
  filekey: string,
  params: DownloadFileParams,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<Blob>(
    {
      url: `/files/${filekey}`,
      method: 'GET',
      params,
      responseType: 'blob',
      signal,
    },
    options,
  )
}

export const getDownloadFileQueryKey = (
  filekey: string,
  params: DownloadFileParams,
) => {
  return [`/files/${filekey}`, ...(params ? [params] : [])] as const
}

export const getDownloadFileQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getDownloadFileQueryKey(filekey, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({
    signal,
  }) => downloadFile(filekey, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!filekey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadFile>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type DownloadFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadFile>>
>
export type DownloadFileQueryError = ErrorType<string>

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Download a file
 */

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getDownloadFileQueryOptions(filekey, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getDownloadFileSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getDownloadFileQueryKey(filekey, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({
    signal,
  }) => downloadFile(filekey, params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof downloadFile>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type DownloadFileSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadFile>>
>
export type DownloadFileSuspenseQueryError = ErrorType<string>

export function useDownloadFileSuspense<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadFileSuspense<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useDownloadFileSuspense<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Download a file
 */

export function useDownloadFileSuspense<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = ErrorType<string>,
>(
  filekey: string,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof downloadFile>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getDownloadFileSuspenseQueryOptions(
    filekey,
    params,
    options,
  )

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
