/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * api
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  GetAllVisionsParams,
  HttpError,
  PaginationVision,
  Vision,
  VisionCreateDto,
  VisionUpdateDto,
} from './api.schemas'

import {apiServiceInstance} from '../../../axios/axios'
import type {ErrorType, BodyType} from '../../../axios/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all visions with pagination and filtering
 */
export const getAllVisions = (
  params?: GetAllVisionsParams,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<PaginationVision>(
    {url: `/vision-simulator`, method: 'GET', params, signal},
    options,
  )
}

export const getGetAllVisionsQueryKey = (params?: GetAllVisionsParams) => {
  return [`/vision-simulator`, ...(params ? [params] : [])] as const
}

export const getGetAllVisionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllVisions>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllVisionsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVisions>>> = ({
    signal,
  }) => getAllVisions(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAllVisions>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetAllVisionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllVisions>>
>
export type GetAllVisionsQueryError = ErrorType<HttpError>

export function useGetAllVisions<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params: undefined | GetAllVisionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllVisions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVisions>>,
          TError,
          Awaited<ReturnType<typeof getAllVisions>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetAllVisions<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllVisions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVisions>>,
          TError,
          Awaited<ReturnType<typeof getAllVisions>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetAllVisions<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllVisions>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get all visions with pagination and filtering
 */

export function useGetAllVisions<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllVisions>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetAllVisionsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetAllVisionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAllVisions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllVisionsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVisions>>> = ({
    signal,
  }) => getAllVisions(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAllVisions>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetAllVisionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllVisions>>
>
export type GetAllVisionsSuspenseQueryError = ErrorType<HttpError>

export function useGetAllVisionsSuspense<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params: undefined | GetAllVisionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAllVisions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetAllVisionsSuspense<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAllVisions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetAllVisionsSuspense<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAllVisions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get all visions with pagination and filtering
 */

export function useGetAllVisionsSuspense<
  TData = Awaited<ReturnType<typeof getAllVisions>>,
  TError = ErrorType<HttpError>,
>(
  params?: GetAllVisionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAllVisions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetAllVisionsSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Create a new vision
 */
export const createVision = (
  visionCreateDto: BodyType<VisionCreateDto>,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<Vision>(
    {
      url: `/vision-simulator`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: visionCreateDto,
      signal,
    },
    options,
  )
}

export const getCreateVisionMutationOptions = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVision>>,
    TError,
    {data: BodyType<VisionCreateDto>},
    TContext
  >
  request?: SecondParameter<typeof apiServiceInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVision>>,
  TError,
  {data: BodyType<VisionCreateDto>},
  TContext
> => {
  const mutationKey = ['createVision']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVision>>,
    {data: BodyType<VisionCreateDto>}
  > = (props) => {
    const {data} = props ?? {}

    return createVision(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreateVisionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createVision>>
>
export type CreateVisionMutationBody = BodyType<VisionCreateDto>
export type CreateVisionMutationError = ErrorType<HttpError>

/**
 * @summary Create a new vision
 */
export const useCreateVision = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createVision>>,
      TError,
      {data: BodyType<VisionCreateDto>},
      TContext
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createVision>>,
  TError,
  {data: BodyType<VisionCreateDto>},
  TContext
> => {
  const mutationOptions = getCreateVisionMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Delete a vision
 */
export const deleteVision = (
  id: string,
  options?: SecondParameter<typeof apiServiceInstance>,
) => {
  return apiServiceInstance<void>(
    {url: `/vision-simulator/${id}`, method: 'DELETE'},
    options,
  )
}

export const getDeleteVisionMutationOptions = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVision>>,
    TError,
    {id: string},
    TContext
  >
  request?: SecondParameter<typeof apiServiceInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVision>>,
  TError,
  {id: string},
  TContext
> => {
  const mutationKey = ['deleteVision']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVision>>,
    {id: string}
  > = (props) => {
    const {id} = props ?? {}

    return deleteVision(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeleteVisionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVision>>
>

export type DeleteVisionMutationError = ErrorType<HttpError>

/**
 * @summary Delete a vision
 */
export const useDeleteVision = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVision>>,
      TError,
      {id: string},
      TContext
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVision>>,
  TError,
  {id: string},
  TContext
> => {
  const mutationOptions = getDeleteVisionMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Get a vision by ID
 */
export const getVisionByID = (
  id: string,
  options?: SecondParameter<typeof apiServiceInstance>,
  signal?: AbortSignal,
) => {
  return apiServiceInstance<Vision>(
    {url: `/vision-simulator/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetVisionByIDQueryKey = (id: string) => {
  return [`/vision-simulator/${id}`] as const
}

export const getGetVisionByIDQueryOptions = <
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisionByID>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetVisionByIDQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisionByID>>> = ({
    signal,
  }) => getVisionByID(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getVisionByID>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetVisionByIDQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVisionByID>>
>
export type GetVisionByIDQueryError = ErrorType<HttpError>

export function useGetVisionByID<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisionByID>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisionByID>>,
          TError,
          Awaited<ReturnType<typeof getVisionByID>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetVisionByID<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisionByID>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisionByID>>,
          TError,
          Awaited<ReturnType<typeof getVisionByID>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetVisionByID<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisionByID>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get a vision by ID
 */

export function useGetVisionByID<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisionByID>>, TError, TData>
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>} {
  const queryOptions = getGetVisionByIDQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetVisionByIDSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getVisionByID>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetVisionByIDQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisionByID>>> = ({
    signal,
  }) => getVisionByID(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getVisionByID>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData>}
}

export type GetVisionByIDSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVisionByID>>
>
export type GetVisionByIDSuspenseQueryError = ErrorType<HttpError>

export function useGetVisionByIDSuspense<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getVisionByID>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetVisionByIDSuspense<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getVisionByID>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
export function useGetVisionByIDSuspense<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getVisionByID>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData>}
/**
 * @summary Get a vision by ID
 */

export function useGetVisionByIDSuspense<
  TData = Awaited<ReturnType<typeof getVisionByID>>,
  TError = ErrorType<HttpError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getVisionByID>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>
} {
  const queryOptions = getGetVisionByIDSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Update a vision
 */
export const updateVision = (
  id: string,
  visionUpdateDto: BodyType<VisionUpdateDto>,
  options?: SecondParameter<typeof apiServiceInstance>,
) => {
  return apiServiceInstance<Vision>(
    {
      url: `/vision-simulator/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: visionUpdateDto,
    },
    options,
  )
}

export const getUpdateVisionMutationOptions = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateVision>>,
    TError,
    {id: string; data: BodyType<VisionUpdateDto>},
    TContext
  >
  request?: SecondParameter<typeof apiServiceInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateVision>>,
  TError,
  {id: string; data: BodyType<VisionUpdateDto>},
  TContext
> => {
  const mutationKey = ['updateVision']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateVision>>,
    {id: string; data: BodyType<VisionUpdateDto>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updateVision(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdateVisionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateVision>>
>
export type UpdateVisionMutationBody = BodyType<VisionUpdateDto>
export type UpdateVisionMutationError = ErrorType<HttpError>

/**
 * @summary Update a vision
 */
export const useUpdateVision = <
  TError = ErrorType<HttpError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateVision>>,
      TError,
      {id: string; data: BodyType<VisionUpdateDto>},
      TContext
    >
    request?: SecondParameter<typeof apiServiceInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateVision>>,
  TError,
  {id: string; data: BodyType<VisionUpdateDto>},
  TContext
> => {
  const mutationOptions = getUpdateVisionMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
